/**
 * AI tools & platforms catalogue for the /ai-integrations hub.
 * Every note describes honestly how AJS works with the tool for clients.
 * Tool names are trademarks of their owners; AJS is not affiliated with them.
 */

export type CatalogTool = { name: string; note: string; href?: string };
export type CatalogCategory = { id: string; title: string; intro: string; tools: CatalogTool[] };

const CODING_COMPARE = "/ai-integrations/compare/cursor-vs-github-copilot-vs-claude-code";
const AUTOMATION_COMPARE = "/ai-integrations/compare/n8n-vs-zapier-vs-make";
const CHATBOTS = "/ai-integrations/ai-chatbot-development";

export const AI_CATALOG: CatalogCategory[] = [
  {
    id: "llm-assistants",
    title: "AI models & assistants",
    intro: "Large language models we connect to your software through their official APIs.",
    tools: [
      { name: "ChatGPT / OpenAI", note: "GPT models wired into apps for chat, summaries, extraction and agents.", href: "/ai-integrations/chatgpt-openai-integration" },
      { name: "Claude (Anthropic)", note: "Long-document analysis, careful reasoning and safe business assistants.", href: "/ai-integrations/claude-ai-integration" },
      { name: "Google Gemini", note: "Multimodal features (text + images) using the Gemini API." },
      { name: "DeepSeek R1", note: "Cost-efficient reasoning model for internal tools and batch jobs." },
      { name: "OpenRouter", note: "One gateway to many models, so apps can switch providers without code changes." },
      { name: "Perplexity AI", note: "Search-grounded answers for research features via its API." },
      { name: "NotebookLM", note: "Recommended to teams for source-grounded research on their own documents." },
      { name: "MiniMax", note: "Evaluated for multilingual chat and voice use cases." },
      { name: "Kimi", note: "Long-context model option for large document workflows." },
    ],
  },
  {
    id: "coding",
    title: "AI coding tools",
    intro: "Assistants our engineers use to ship faster, always with human code review.",
    tools: [
      { name: "Cursor", note: "AI-first editor used for refactors and multi-file changes.", href: CODING_COMPARE },
      { name: "GitHub Copilot", note: "Inline completions and pull-request help inside the IDE.", href: CODING_COMPARE },
      { name: "Claude Code", note: "Terminal agent for larger codebase tasks and test writing.", href: CODING_COMPARE },
      { name: "Copilot Workspace", note: "Planning issues into code changes on GitHub." },
      { name: "Base44", note: "AI app builder we use to set up and extend client projects." },
      { name: "Lovable", note: "Fast UI prototypes that we then harden into production code." },
      { name: "v0 by Vercel", note: "Generating React UI drafts before engineering polish." },
      { name: "Bolt.new", note: "Quick full-stack demos to validate an idea with a client." },
      { name: "Replit Agent", note: "Throwaway prototypes and proof-of-concepts." },
      { name: "Google Antigravity", note: "Agentic development environment we track for team workflows." },
      { name: "Devin AI", note: "Autonomous engineering agent we evaluate for routine tasks." },
      { name: "SWE-agent", note: "Open-source agent for automated bug-fixing research." },
      { name: "Aider", note: "Git-aware pair programming in the terminal." },
      { name: "Anysphere", note: "The company behind Cursor." },
      { name: "Tabnine", note: "Private, self-hostable completions for strict-privacy clients." },
      { name: "Codeium", note: "AI completions across many editors." },
      { name: "Amazon Q", note: "AWS-aware coding and cloud troubleshooting help." },
      { name: "Sourcegraph Cody", note: "Codebase-wide search and answers for large repositories." },
      { name: "Blackbox AI", note: "Code search and snippet generation." },
      { name: "Phind", note: "Developer-focused AI search for technical answers." },
      { name: "MutableAI", note: "AI documentation and code understanding." },
      { name: "Warp AI", note: "AI terminal for commands and scripts." },
      { name: "Fig", note: "Terminal autocomplete (now part of Amazon Q)." },
      { name: "Z.ai / zCode", note: "Coding model option evaluated for development workflows." },
    ],
  },
  {
    id: "frameworks",
    title: "AI agent frameworks",
    intro: "Open-source building blocks we use to build custom AI agents and RAG systems.",
    tools: [
      { name: "LangChain", note: "Chains, tools and retrieval pipelines for LLM apps." },
      { name: "LlamaIndex", note: "Connecting company documents to AI search (RAG)." },
      { name: "CrewAI", note: "Multi-agent teams that split complex tasks." },
      { name: "AutoGen", note: "Microsoft's framework for conversational multi-agent systems." },
      { name: "Semantic Kernel", note: "AI orchestration for .NET and enterprise stacks." },
      { name: "Flowise / FlowiseAI", note: "Visual builder for LangChain flows clients can edit." },
      { name: "Langflow", note: "Drag-and-drop AI pipelines for rapid iteration." },
      { name: "AutoGPT", note: "Early autonomous-agent pattern; we apply its lessons, not in production." },
      { name: "BabyAGI", note: "Task-planning agent pattern used for experiments." },
      { name: "Fixie", note: "Hosted agent platform we have evaluated." },
      { name: "Kapa.ai", note: "AI answers over technical documentation." },
      { name: "Mendable", note: "Docs chatbot for developer products." },
    ],
  },
  {
    id: "automation",
    title: "Workflow automation",
    intro: "Connecting apps so repetitive work runs on its own.",
    tools: [
      { name: "n8n", note: "Self-hosted automations with full data control.", href: "/ai-integrations/n8n-make-automation" },
      { name: "Make.com", note: "Visual multi-step scenarios for operations teams.", href: "/ai-integrations/n8n-make-automation" },
      { name: "Zapier AI", note: "Quick SaaS-to-SaaS automations.", href: AUTOMATION_COMPARE },
      { name: "Activepieces", note: "Open-source Zapier alternative." },
      { name: "Tray.io", note: "Enterprise integration platform." },
      { name: "Workato", note: "Enterprise automation with governance." },
      { name: "UiPath Studio", note: "RPA for legacy desktop systems without APIs." },
      { name: "Automation Anywhere", note: "Enterprise RPA bots." },
      { name: "Blue Prism", note: "Regulated-industry RPA." },
    ],
  },
  {
    id: "chatbots",
    title: "Chatbots & conversational AI",
    intro: "Customer-facing bots for websites, WhatsApp and support desks.",
    tools: [
      { name: "Voiceflow", note: "Designing chat and voice assistants collaboratively.", href: CHATBOTS },
      { name: "Botpress", note: "LLM-powered bots with knowledge bases.", href: CHATBOTS },
      { name: "Rasa", note: "Open-source, on-premise conversational AI.", href: CHATBOTS },
      { name: "Dialogflow", note: "Google's intent-based bots for web and phone." },
    ],
  },
  {
    id: "voice",
    title: "Voice & audio AI",
    intro: "Speech generation, voice agents and audio clean-up.",
    tools: [
      { name: "ElevenLabs", note: "Natural multilingual voices and voice agents.", href: "/ai-integrations/ai-voice-agents" },
      { name: "Murf AI", note: "Voiceovers for training and product videos." },
      { name: "Play.ht", note: "Text-to-speech API for apps." },
      { name: "Lovo.ai", note: "Voiceover and video narration." },
      { name: "Resemble.ai", note: "Custom voice cloning with consent controls." },
      { name: "Speechify", note: "Read-aloud accessibility features." },
      { name: "Suno", note: "AI music for marketing content." },
      { name: "Descript", note: "Editing audio/video by editing the transcript." },
      { name: "Riverside.fm", note: "Remote recording for podcasts and interviews." },
      { name: "Podcastle", note: "Podcast recording and AI clean-up." },
      { name: "Adobe Podcast", note: "One-click speech enhancement." },
      { name: "Auphonic", note: "Automatic audio levelling and noise reduction." },
      { name: "Granola", note: "AI meeting notes for client calls." },
    ],
  },
  {
    id: "video-design",
    title: "Video, image & design AI",
    intro: "Creative tools used for product demos, marketing and UI assets.",
    tools: [
      { name: "Midjourney", note: "Concept art and marketing imagery." },
      { name: "Canva Magic Studio", note: "Fast branded social creatives." },
      { name: "Adobe Firefly", note: "Commercially safe generative images." },
      { name: "Gamma AI", note: "Pitch decks and proposals." },
      { name: "HeyGen", note: "AI avatar videos for explainers." },
      { name: "Synthesia", note: "Training videos with AI presenters." },
      { name: "Colossyan", note: "L&D video creation." },
      { name: "DeepBrain AI", note: "AI avatar and news-style videos." },
      { name: "D-ID", note: "Talking-photo avatars via API." },
      { name: "Synthesys", note: "Voice and avatar video generation." },
      { name: "RunwayML / Gen-3", note: "Generative video and editing." },
      { name: "Pika Labs", note: "Short generative video clips." },
      { name: "Sora", note: "OpenAI's text-to-video model." },
      { name: "Kaiber", note: "Stylised music-driven video." },
    ],
  },
  {
    id: "writing-seo",
    title: "Writing, SEO & productivity",
    intro: "Tools for content, research and everyday productivity.",
    tools: [
      { name: "Notion AI", note: "Project docs and meeting summaries." },
      { name: "Jasper AI", note: "Brand-voice marketing copy." },
      { name: "Copy.ai", note: "Sales and marketing copy workflows." },
      { name: "Writesonic", note: "Blog drafts and SEO articles." },
      { name: "Anyword", note: "Performance-scored ad copy." },
      { name: "Writer.com", note: "Enterprise writing with style guides." },
      { name: "ContentAtScale", note: "Long-form content generation." },
      { name: "SurferSEO", note: "On-page SEO content scoring." },
      { name: "Frase.io", note: "SEO briefs from search results." },
      { name: "MarketMuse", note: "Content planning and topic authority." },
      { name: "Scalenut", note: "SEO content planning and writing." },
      { name: "Grammarly", note: "Grammar and tone checks." },
      { name: "QuillBot", note: "Paraphrasing and summarising." },
      { name: "Hemingway Editor", note: "Readability improvements." },
      { name: "DeepL Translator", note: "High-quality translation for multilingual sites." },
      { name: "Feedly AI", note: "Market and tech news monitoring." },
      { name: "Inoreader", note: "RSS research feeds." },
    ],
  },
];

export const AI_CATALOG_TOOL_COUNT = AI_CATALOG.reduce((sum, c) => sum + c.tools.length, 0);
