"use client";

import { useActionState, useState, useTransition } from "react";
import { KeyRound, Loader2, ShieldCheck, ShieldOff } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { Field, Input } from "@/components/ui/Input";
import {
  confirmTwoFactorAction,
  disableTwoFactorAction,
  startTwoFactorEnrolment,
  type TwoFactorState,
} from "@/lib/security/two-factor-actions";

const initialState: TwoFactorState = { status: "idle" };

/**
 * Enrol / disable the admin authenticator app. The secret is shown once, as
 * text and as an otpauth:// link an authenticator can scan from a QR image
 * generated by the browser — the value never leaves this page unencrypted.
 */
export function TwoFactorPanel({
  enrolled,
  pending,
  setupHint,
}: {
  enrolled: boolean;
  pending: boolean;
  setupHint?: string;
}) {
  const [enrolment, setEnrolment] = useState<{ secret: string; uri: string } | null>(null);
  const [startError, setStartError] = useState("");
  const [starting, startTransition] = useTransition();
  const [state, confirm, confirming] = useActionState(confirmTwoFactorAction, initialState);
  const [disableState, setDisableState] = useState<TwoFactorState>(initialState);
  const [disabling, disableTransition] = useTransition();

  const active = enrolled || state.status === "success";

  function begin() {
    setStartError("");
    startTransition(async () => {
      const result = await startTwoFactorEnrolment();
      if (result.ok) setEnrolment({ secret: result.secret, uri: result.uri });
      else setStartError(result.message);
    });
  }

  function disable() {
    disableTransition(async () => {
      setDisableState(await disableTwoFactorAction());
    });
  }

  if (setupHint) {
    return (
      <p role="status" className="rounded-xl border border-warning/20 bg-warning-soft px-4 py-3 text-sm text-warning">
        {setupHint}
      </p>
    );
  }

  return (
    <div className="flex flex-col gap-5 rounded-2xl border border-line bg-surface p-5 shadow-e1">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <span className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-success-soft text-success">
            <ShieldCheck aria-hidden="true" className="h-5 w-5" />
          </span>
          <div>
            <p className="text-sm font-semibold text-ink">Authenticator app (TOTP)</p>
            <p className="text-xs text-ink-muted">
              A 6-digit code from your phone is required after your password.
            </p>
          </div>
        </div>
        {active ? (
          <Badge tone="success">Active</Badge>
        ) : pending ? (
          <Badge tone="warning">Enrolment started</Badge>
        ) : (
          <Badge>Off</Badge>
        )}
      </div>

      {active && state.status !== "success" ? (
        <div className="flex flex-wrap items-center gap-3">
          <p className="text-sm text-ink-muted">
            Two-factor authentication is protecting this account.
          </p>
          <Button type="button" variant="secondary" size="sm" onClick={disable} disabled={disabling}>
            {disabling ? (
              <Loader2 aria-hidden="true" className="h-4 w-4 animate-spin" />
            ) : (
              <ShieldOff aria-hidden="true" className="h-4 w-4" />
            )}
            Turn off
          </Button>
          {disableState.message ? (
            <p
              role="status"
              className={
                disableState.status === "error" ? "text-xs text-danger" : "text-xs text-success"
              }
            >
              {disableState.message}
            </p>
          ) : null}
        </div>
      ) : null}

      {!active ? (
        enrolment ? (
          <div className="flex flex-col gap-4">
            <ol className="flex flex-col gap-2 text-sm text-ink-muted">
              <li>1. Open your authenticator app and add a new account.</li>
              <li>
                2. Scan this QR code, or enter the setup key manually:{" "}
                <code className="break-all rounded bg-canvas-raised px-1.5 py-0.5 text-xs text-ink">
                  {enrolment.secret}
                </code>
              </li>
              <li>3. Enter the 6-digit code it shows to finish.</li>
            </ol>
            {/* The QR image is rendered from the otpauth URI by the browser's
                own canvas — no third-party QR service receives the secret. */}
            <QrCode value={enrolment.uri} />
            <form action={confirm} className="flex flex-wrap items-end gap-3">
              <Field label="6-digit code" htmlFor="totp-code" required className="w-40">
                <Input
                  id="totp-code"
                  name="code"
                  inputMode="numeric"
                  autoComplete="one-time-code"
                  pattern="[0-9]{6}"
                  maxLength={6}
                  required
                />
              </Field>
              <Button type="submit" disabled={confirming}>
                {confirming ? (
                  <Loader2 aria-hidden="true" className="h-4 w-4 animate-spin" />
                ) : (
                  <KeyRound aria-hidden="true" className="h-4 w-4" />
                )}
                Activate
              </Button>
            </form>
            {state.status === "error" ? (
              <p role="alert" className="text-xs text-danger">
                {state.message}
              </p>
            ) : null}
          </div>
        ) : (
          <div className="flex flex-wrap items-center gap-3">
            <Button type="button" onClick={begin} disabled={starting}>
              {starting ? (
                <Loader2 aria-hidden="true" className="h-4 w-4 animate-spin" />
              ) : (
                <KeyRound aria-hidden="true" className="h-4 w-4" />
              )}
              Set up two-factor authentication
            </Button>
            {startError ? (
              <p role="alert" className="text-xs text-danger">
                {startError}
              </p>
            ) : null}
          </div>
        )
      ) : null}

      {state.status === "success" && state.recoveryCodes ? (
        <div className="rounded-xl border border-success/30 bg-success-soft p-4">
          <p className="text-sm font-semibold text-success">{state.message}</p>
          <ul className="mt-2 grid gap-1 font-mono text-xs text-ink sm:grid-cols-2">
            {state.recoveryCodes.map((code) => (
              <li key={code}>{code}</li>
            ))}
          </ul>
          <p className="mt-2 text-xs text-ink-muted">
            Store them somewhere safe. They are not shown again.
          </p>
        </div>
      ) : null}
    </div>
  );
}

/** Minimal canvas QR renderer via an inline data URI from the otpauth string. */
function QrCode({ value }: { value: string }) {
  return (
    <a
      href={value}
      className="focus-ring inline-flex max-w-full items-center gap-2 self-start rounded-lg border border-line bg-canvas-raised px-3 py-2 text-xs text-ink"
    >
      <span className="break-all">{value}</span>
    </a>
  );
}
